/**
 * 全ユーザー共通のデフォルトカテゴリと、カード明細インポート時の自動振り分けキーワードの定義。
 *
 * `key` はDB上の `categories.default_key` に対応する安定識別子で、リネームがあっても
 * 既存ユーザーの行と対応づけるために使う。`parentKey` は親カテゴリの `key` を指す。
 * `sort_order` はこの配列内で同じ `parentKey`（親を持たない場合は種別を問わずルート同士）を
 * 持つ要素の出現順から算出する（`scripts/generate-default-categories-migration.ts` 参照）。
 */

export type DefaultCategoryType = "income" | "expense";

export type DefaultCategoryDef = {
  key: string;
  name: string;
  type: DefaultCategoryType;
  color: string | null;
  parentKey?: string;
  importKeywords?: string[];
};

export const DEFAULT_CATEGORIES: DefaultCategoryDef[] = [
  { key: "living", name: "生活費", type: "expense", color: "#22c55e" },
  {
    key: "dining_out",
    name: "外食費",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: [
      "マクドナルド",
      "ラーメン",
      "チュウカソバ",
      "ウドン",
      "ヤマオカヤ",
      "丸亀",
      "マルガメ",
      "ガスト",
      "ジョナサン",
      "バーガーキング",
      "ヨシノヤ",
      "吉野家",
      "YOSHINOYA",
      "サイゼリヤ",
      "スシロー",
      "はま寿司",
      "HAMAZUSHI",
      "ハマズシ",
      "スターバックス",
      "コメダ",
      "コーヒー",
      "食堂",
      "ギュウカク",
      "GYUKAKU",
      "ケンタッキー",
      "ビックリドンキ",
      "ツケメン",
      "松屋",
      "マツヤ",
      "ナカウ",
      "ミスタードーナツ",
      "ミスド",
      "ピザハット",
      "ドミノピザ",
      "キッチンオリジン",
      "マリオンクレープ",
      "ウシノヤ",
      "油堂",
      "アブラトウ",
      "ブブカ",
      "チョップス",
      "キッチンメープル",
      "アラシヤマチャヤ",
      "カンダダルマ",
      "イチバンガイ",
      "グランスタ",
      "エキュート",
      "旬味館",
      "ケンバイキ",
    ],
  },
  {
    key: "daily_goods",
    name: "日用品",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: [
      "セブン",
      "ローソン",
      "セイコーマート",
      "ファミリーマート",
      "FAMILYMART",
      "ミニストップ",
      "NEWDAYS",
      "ナチュラルローソン",
      "キヨスク",
      "JRCROSS",
      "自販機",
      "ジハンキ",
      "自動販売",
      "ジドウハンバイ",
      "ユウビン",
      "サガワ",
      "ドンキホーテ",
      "ムジルシ",
      "ニトリ",
      "ダイソー",
      "セリア",
      "ツルハ",
      "サンドラッグ",
      "ドラッグ",
      "マツモトキヨシ",
      "ウエルシア",
      "ココカラ",
      "ヤッキョク",
      "コクミン",
      "アークス",
      "ホクレン",
      "イオン",
      "ヨドバシ",
      "セイユウ",
      "コープ",
      "セイキョウ",
      "ビッグハウス",
      "ハセガワストア",
      "シャトレーゼ",
      "ディーシーエム",
      "ヒャッカテン",
      "ハンズ",
      "ヤクルト",
      "オダキュウオ",
      "ハマダデンキ",
    ],
  },
  {
    key: "transportation",
    name: "交通費",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: [
      "スイカ",
      "SUICA",
      "パスモ",
      "PASMO",
      "タイムズカー",
      "リパーク",
      "タクシー",
      "GOアプリ",
      "ゴアプリ",
      "バス",
      "チカテツ",
      "コウツウ",
      "ジェイアール",
      "イサリビ",
      "ジョウシャ",
      "モダセキユ",
    ],
  },
  {
    key: "hot_spring",
    name: "温泉",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: ["オンセン"],
  },
  {
    key: "utilities_communication",
    name: "光熱費・通信費",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: [
      "POVO",
      "ポヴォ",
      "ニホンツウシン",
      "JAPAN COMMUNICATIONS",
      "ホッカイドウデンリ",
    ],
  },
  {
    key: "medical",
    name: "医療",
    type: "expense",
    color: "#22c55e",
    parentKey: "living",
    importKeywords: [
      "クリニック",
      "ヒフカ",
      "チョウザイ",
      "インコウカ",
      "ビョウイン",
      "歯科",
      "イイン",
    ],
  },
  { key: "entertainment", name: "娯楽", type: "expense", color: "#ef4444" },
  {
    key: "subscription",
    name: "サブスク",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
    importKeywords: [
      "CLAUDE",
      "SPOTIFY",
      "YOUTUBE",
      "APPLE",
      "アップル",
      "GOOGLE",
      "グーグル",
      "CHATGPT",
      "OPENAI",
      "1PASSWORD",
      "VERCEL",
      "CURSOR",
      "GITHUB",
      "STEAM",
      "HOYOVERSE",
      "DISCORD",
      "ADOBE",
      "NETFLIX",
      "CLOUDFLARE",
      "TURSO",
      "SURFSHARK",
      "PADDLE",
      "ITCH.IO",
      "DMM",
      "ディーエムエム",
      "モリサワ",
      "SQUARE ENIX",
      "プライム",
      "ネツトフリツクス",
      "アベマ",
      "ABEMA",
      "UNCLUTTER",
      "PIXIV",
      "クリプトン",
      "ABLETON AG"
    ],
  },
  {
    key: "hobby",
    name: "趣味",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
  },
  {
    key: "hobby_music",
    name: "趣味(音楽)",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
  },
  {
    key: "travel",
    name: "旅行",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
    importKeywords: [
      "JAL",
      "ジャル",
      "ANA",
      "エーエヌエー",
      "ジェットスター",
      "エアドゥ",
      "ピーチアビエ",
      "空港",
      "クウコウ",
      "航空",
      "コウクウ",
      "スカイショップ",
      "ニュースター",
      "NEWSTAR",
      "スカイライナー",
      "エキネット",
      "ホテル",
      "キングダム",
      "AGODA",
      "ミチノエキ",
      "ブッサンカン",
      "ヤツハシ",
      "ウミホタル",
      "北彩館",
      "レンガテラス",
      "オミヤゲ",
      "ミソギノサト",
    ],
  },
  {
    key: "event",
    name: "イベント",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
    importKeywords: [
      "ｻﾞｲｺｶﾌﾞｼｷｶﾞｲｼｬ",
    ]
  },
  {
    key: "expensive_goods",
    name: "高額製品",
    type: "expense",
    color: "#ef4444",
    parentKey: "entertainment",
  },
  {
    key: "other_expense",
    name: "その他",
    type: "expense",
    color: "#eab308",
    importKeywords: [],
  },
  {
    key: "reimbursement_expense",
    name: "立て替え",
    type: "expense",
    color: "#eab308",
    parentKey: "other_expense",
  },
  {
    key: "refund",
    name: "払い戻し",
    type: "expense",
    color: "#eab308",
    parentKey: "other_expense",
  },
  { key: "salary", name: "給与", type: "income", color: "#3b82f6" },
  { key: "remittance", name: "仕送り", type: "income", color: "#a855f7" },
  { key: "windfall", name: "臨時収入", type: "income", color: "#a855f7" },
  { key: "other_income", name: "その他", type: "income", color: "#eab308" },
  {
    key: "reimbursement_income",
    name: "立て替え",
    type: "income",
    color: "#eab308",
    parentKey: "other_income",
  },
  {
    key: "refund_income",
    name: "払い戻し",
    type: "income",
    color: "#eab308",
    parentKey: "other_income",
  },
];
